.:
  name: .
  description: 根目录，按照内容与来源分类
交换:
  name: 交换
  description: 本目录包含了一系列与性转和跨性别主题相关的小说，作品通过各式各样的情节探讨了角色的性别认同和自我探索。这些作品既具有奇幻的色彩，又深刻反映了人类对性别和身份认知的思考。例如，《47岁的已婚大叔，变成了自己儿子的女友》讲述了一个中年男性在意外的情况下转换为女性，并面临家庭及社会关系的重新审视和挑战。并且，在《DSE系列－死星終、侵蝕、傷跡》中，角色的变化不仅涉及外观的突变，也伴随着心理状态的激烈挣扎，映射出对身份和归属的深入探索。此外，像《Gnow_Grave『人偶－幸福的暗轉、終焉的信念－』》等作品以奇幻色彩为背景，深化了情节的复杂性及角色的内心冲突。此目录中的作品也可能包含一些成年人内容，适合需要探索性别和身份议题的读者。
催眠:
  name: 催眠
  description: 该目录涵盖了一系列与催眠、变身以及性别转换相关的小说，其中包含了不同类型的故事情节，如催眠带来的性别转变、自我认知的探索以及多元性别主题的探讨。作品涉及的内容广泛，包括了催眠系统的设定、角色的心理变化以及与性别认同相关的挑战。此目录中的许多作品都展示了通过催眠引导角色进行外形和性别的转换。例如，《女体催眠机器》主题围绕着使用催眠技巧改变角色的生理性别和社会角色，而《我是谁？》则引发了关于自我认同的思考。
其他:
  name: 其他
  description: 本目录包含了多种主题的性转、变身和跨性别相关小说作品，共计20个文件，涉及不同的角色性别转换情节和身份探索。作品如《教室六部曲》是一部完结的微小说，基于青春校园环境，讲述了角色在教室内外的情感与性别认同的碰撞。另一部《超凡“易”生》则围绕着一个少年通过特殊方法获得新身份的非凡体验，探讨了变身带来的自我认知。目录中的《2022年男孩子改造计划》系列描绘了几个男孩在特定环境下经历性别转变与社会认同的复杂过程，包含有趣和发人深省的故事情节。同时，《CD世界OL》系列作品则包含了多部以科幻背景为概念的变身情节，特别是与性别和生理性别变化相关的凌辱与冒险元素，该系列包含多个章节，构建了一个多层次的虚拟世界。每个文件通过故事情节展示不同角色的自我探索和性别认同问题，可能包含一些适龄且有争议的内容。
变性:
  name: 变性
  description: 本仓库的‘变性’目录包含多个与性别转换、伪娘、变身及跨性别主题相关的文本，旨在为研究者提供丰富的文学资料。目录中的作品多集中在描绘角色经历性别转换的故事情节，其中一些作品可能会涉及到角色在转变过程中的心理变化与自我探索。这些小说不仅展示了角色外表和生理上的变化，也深刻探讨了个人在性别认同与社会接受之间的矛盾。例如，作品《DTX之新生-1》到《DTX之新生-10（终章）》系列小说，展现了一位男主角在经历性别变换后的生活及内心挣扎，描绘了他如何重新定义自己的身份。其他作品如《AV改变我（9000字上集）》则通过戏剧性的变身情节，引导读者思考性别与社会角色的关系。这些小说中的情节充满了幻想与反思，适合喜爱探索多元性别主题的读者。
变装:
  name: 变装
  description: 本目录为多元性别相关的档案，重点收录了各类与变装、性别转换及跨性别主题相关的小说。作品涉及性别认同和自我探索的深入探讨，涵盖多样化的情节设定。目录中包括多个系列文件，如《CDTG系统》系列，该系列关注角色在CDTG（即“变装”）系统下的性别变化及其带来的内心冲突；还有各种变身的小说，如《The
    Making of a Maid》，探讨角色如何在变装与自我认知之间挣扎；同样，《Caught By My Wife》等作品则通过家庭与伴侣的视角探讨性别和身份的问题。整体来看，目录集合了极具幻想色彩，并穿插现实问题的小说作品，适合对性别多样性和变装文化感兴趣的研究者与读者。
变身:
  name: 变身
  description: 本目录包含了一系列以性别转变和跨性别主题为核心的小说和杂志资料，包括不同的故事情节和角色设定。目录中的文本涵盖了丰富的故事情节和复杂的人物关系，例如‘[变身]CdBook杂志：创刊号’为读者介绍了该系列的背景和创作理念，而‘[变身]_(新人报到)_双子星实验_第一部(Kinder281)’则集中描绘了一种实验导致的人物性别和身份转变，探讨了角色的内心冲突与自我认同的历程。此外，‘[变身]007：铁金刚永化艳女郎’系列通过动作与冒险的视角，展现了一个男性角色被转化为女性的奇妙历程，进一步引发了关于性别认同和社会期望的讨论。在‘[变身]_108欲魔器--副器--躯’系列中，情节围绕欲望和变身的复杂关系，将性转与个人欲望的纠葛进行了深入的探讨。此类作品通常涉及生理性别与心理性别不一致的深刻主题，反映出作者对性别多元性的思考和表达。
改造:
  name: 改造
  description: 本仓库专注于多元性别主题的小说，特别是涉及性别转换、变身以及跨性别相关的作品。这里收录了大量关于伪娘、男娘、变身及其衍生故事的小说，探索角色在性别转换过程中的心理变化、自我认同及其社会影响。每个作品都在某种程度上探讨了性别认同、自我探索以及社会接受度等主题。我们提供的信息包括小说的标题、主要情节及其对表现性别流动性和转换的理解。
皮物:
  name: 皮物
  description: 本目录收录了多部围绕性别转换、伪娘、变身及跨性别主题的小说。包括了性转小说中的典型情节，如角色在不同场景下的性别变化与身份探索。具体作品如《毁灭者—新生》中主角经历了毁灭与重生的双重过程，探讨了性别认同与自我发现的主题。还有《错乱》系列，展现了一位角色在多次性别变换中对自身身份的挣扎与理解。此外，《不可能的高度》和《被套路的可爱小巫师》同样涉及角色在变身过程中的冒险，以及如何处理与周围人在性别表现上的差异。整个系列的内容适合进行关于性别认同和自我探索的科学研究与学习。
资源:
  name: 资源
  description: 本目录涵盖了一系列多元性别相关的小说，包括伪娘、跨性别和变身等主题，反映了性别认同与自我探索的复杂性。这些作品中不少具有深刻的心理描写，关注角色在性别转变过程中的内心挣扎与认同。例如，《变身上司》和《老师不容易》探讨了在职场中性别认同对人际关系的影响；而《金枝奇缘》系列则通过历史背景下的性别角色反转，生动地描绘了不同性别身份下的情感纠葛。作品《欲魔器》系列则融合了奇幻与超现实元素，展示了更为复杂的性别与自我认同交织的故事情节。
附身:
  name: 附身
  description: 本目录包含多个作品，涉及穿越、附身及欲魔器等奇幻主题。作品中的角色通过不同的情节进入其他角色的身体，实现性别转变或身份替换。例如，《穿越时空的入替之岳母》讲述了主人公通过时空穿越，接替了一位女性角色的身份，让故事充满了性别议题与个人身份的探索。另一部作品《我的基友会附身》则聚焦于角色间复杂的友谊与爱情关系，男主在获得附身能力后，面临新的自我认知与成长。此外，多个与“欲魔器”相关的作品，如《108欲魔器--副器--太极子母镜》及各种附属作品，集中在角色通过神秘物品进行的改变与奇遇。这些作品通常围绕着角色的内心挣扎与自我认同，反映了多样化的性别观念与社会关系，既带有奇幻色彩，又不乏现实世界的隐喻与思考。
